export const DynamicAsideMenuConfig = {
	items: [
		{
			title: 'Dashboards',
			root: true,
			show: true,
			icon: 'flaticon2-dashboard',
			svg: './assets/media/svg/icons/Design/Layers.svg',
			page: '/dashboard',
			bullet: 'dot',
		},
		{
			title: 'Layout Builder',
			root: true,
			show: true,
			icon: 'flaticon2-expand',
			page: '/builder',
			svg: './assets/media/svg/icons/Home/Library.svg',
		},
		{ section: 'Lists' },
		{
			title: 'Users',
			root: true,
			show: false,
			icon: 'flaticon2-world',
			page: '/users',
			svg: './assets/media/svg/icons/General/User.svg',
		},
		{
			title: 'Brands',
			root: true,
			show: false,
			icon: 'flaticon2-world',
			page: '/brands',
			svg: './assets/media/svg/icons/Design/Interselect.svg',
		},
		{
			title: 'Items',
			root: true,
			show: false,
			icon: 'flaticon2-world',
			page: '/items/list',
			svg: './assets/media/svg/icons/Layout/Layout-4-blocks.svg',
		},
		{ section: 'Accounts' },
		{
			title: 'Sales',
			root: true,
			show: true,
			icon: 'flaticon2-world',
			page: '/sales',
			svg: './assets/media/svg/icons/Shopping/Money.svg',
		},
		{
			title: 'Purchases',
			root: true,
			show: true,
			icon: 'flaticon2-world',
			page: '/purchases',
			svg: './assets/media/svg/icons/Shopping/Price1.svg',
		},
		{
			title: 'Ledger',
			root: true,
			show: true,
			icon: 'flaticon2-world',
			page: '/ledger',
			svg: './assets/media/svg/icons/Files/Folder.svg',
		},
	],
};
